# Generated by Django 2.2.28 on 2025-03-10 21:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Cuisines',
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('difficulty', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=40, unique=True)),
                ('time_taken', models.IntegerField()),
                ('instructions', models.TextField()),
                ('portion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('picture', models.ImageField(upload_to='recipe_images')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.UserProfile')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.Cuisine')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.Difficulty')),
            ],
            options={
                'verbose_name_plural': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.UserProfile')),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.UserProfile')),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
