# Generated by Django 2.2.28 on 2025-03-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name_plural': 'Difficulties'},
        ),
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name_plural': 'Favourites'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
