# Generated by Django 2.2.28 on 2025-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_auto_20250327_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(error_messages={'unique': 'This recipe name is already taken. Please choose a different name.'}, max_length=40, unique=True),
        ),
    ]
